#pragma once

// Linux
#include <sys/inotify.h>

// C++
#include <optional>
#include <string_view>

// cosmos
#include <cosmos/BitMask.hxx>
#include <cosmos/fs/File.hxx>
#include <cosmos/SysString.hxx>

namespace cosmos {

/// File system event monitoring based on the inotify API.
/**
 * Each instance of INotify maintains a list of watches which are individually
 * added and removed via `addWatch()` and `removeWatch()`. Events for the
 * watched file system objects are queued in the kernel and can be retrieved
 * via `readEvent()`. Upon read an `Event` data structure is returned
 * describing which watched file system object changed.
 *
 * Upon destruction of an `INotify` instance any watches still active on it
 * will automatically be freed.
 *
 * The inotify API operates on individual inodes of the watched filesystem
 * objects which can lead to a number of peculiarities and limitations in its
 * use. Following is a list of documented limitations:
 *
 * - operations on any other (hard) links of a monitored file will also
 *   generate events. This does not apply to events happening to files within
 *   a monitored directory, however. In this case events will only be
 *   generated when the operation was exactly performed on the link found in
 *   the monitored directory.
 * - successive inotify events of the same type will be merged in the kernel
 *   queue, if possible. This saves space in the queue but means that the API
 *   cannot be used to count events on files.
 * - the API cannot be used to distinguish different processes generating
 *   events. The monitoring application can also not keep apart events it may
 *   generate itself from events generated by other processes.
 * - the API does not catch file modifications performed by remote systems in
 *   the case of network file systems.
 * - the API does not work on pseudo file systems like /proc and /sys.
 * - by the time an inotify event is read by the application the name of the
 *   affected file might already have changed again.
 * - The API is not well suited for performing recursive directory tree or
 *   filesystem-wide monitoring, because every directory to be monitored needs
 *   to be explicitly added by the application.
 *
 * The currently registered watches for an inotify file descriptor can be
 * introspected during runtime via `/proc/<pid>/fdinfo/<fd>`.
 **/
class COSMOS_API INotify {
public: // types

	/// Event types that can be monitored.
	enum class EventType : uint32_t {
		/// file access e.g. read(), execve().
		ACCESS        = IN_ACCESS,
		/// metadata changes (e.g. chmod(), utimesat(), chown()).
		ATTRIB        = IN_ATTRIB,
		/// a file which was opened for writing is closed.
		CLOSE_WRITE   = IN_CLOSE_WRITE,
		/// a file which was not opened for writing is closed.
		CLOSE_NOWRITE = IN_CLOSE_NOWRITE,
		/// both of CLOSE_WRITE and CLOSE_NOWRITE.
		CLOSED        = IN_CLOSE,
		/// a new file object was created in a watched directory
		/**
		 * this covers activities like open(), mkdir(), link(),
		 * symlink(), bind() with UNIX domain sockets.
		 **/
		CREATE        = IN_CREATE,
		/// a file object is deleted in a watched directory.
		DELETE        = IN_DELETE,
		/// the watched object itself is deleted.
		DELETE_SELF   = IN_DELETE_SELF,
		/// the watched file is modified (write(), truncate())
		MODIFY        = IN_MODIFY,
		/// the watched object itself has moved.
		MOVE_SELF     = IN_MOVE_SELF,
		/// rename() reported on the directory containing the old name.
		MOVED_FROM    = IN_MOVED_FROM,
		/// rename() reported on the directory containing the new name.
		MOVED_TO      = IN_MOVED_TO,
		/// both of MOVED_FROM and MOVED_TO.
		MOVED         = IN_MOVE,
		/// the watched object was opened.
		OPEN          = IN_OPEN,
		/// all available events.
		ALL_EVENTS    = IN_ALL_EVENTS,
	};

	using enum EventType;

	using EventTypes = BitMask<EventType>;

	/// Additional event flags that can be seen upon receiving inotify events.
	enum class EventFlag : uint32_t {
		/// The watch was removed.
		/**
		 * This can happen due to an explicit call to `removeWatch()`,
		 * or due to the watched filesystem object being deleted, or
		 * due the filesystem containing the object being unmounted.
		 **/
		IGNORED       = IN_IGNORED,
		/// The event relates to a directory object in a watched directory..
		ISDIR         = IN_ISDIR,
		/// The inotify kernel queue overflowed.
		/**
		 * More than `max_queued_events` have been queued for the
		 * inotify instance and some events have been dropped.
		 **/
		OVERFLOW      = IN_Q_OVERFLOW,
		/// The filesystem containing the watched object was unmounted.
		/**
		 * An IGNORED event will also be sent for the affected
		 * WatchID.
		 **/
		UNMOUNT       = IN_UNMOUNT
	};

	using enum EventFlag;

	using EventFlags = BitMask<EventFlag>;

	/// Flags which control the properties of newly added watches.
	enum class WatchFlag : uint32_t {
		/// Don't follow symbolic links in the watch path.
		DONT_FOLLOW = IN_DONT_FOLLOW,
		/// Don't generate events for children of a directory after they have been unlinked.
		EXCL_UNLINK = IN_EXCL_UNLINK,
		/// add events to existing mask if possible.
		/**
		 * If the same path is already watched add the given events to
		 * the current mask, otherwise the mask is replaced by the new
		 * mask.
		 **/
		MASK_ADD    = IN_MASK_ADD,
		/// Only monitor until one event occurs then remove the watch automatically again.
		ONESHOT     = IN_ONESHOT,
		/// Only establish the watch if the given path is a directory.
		/**
		 * If the condition is not met then the call fails with ENOTDIR.
		 **/
		ONLY_DIR    = IN_ONLYDIR,
		/// Watch the given path only if no watch has yet been established for it.
		/**
		 * If the condition is not met then the call fails with EEXIST.
		 **/
		MASK_CREATE = IN_MASK_CREATE
	};

	using enum WatchFlag;

	using WatchFlags = BitMask<WatchFlag>;

	/// Flags used during initialization of a new INotify instance.
	enum class InitFlag : int {
		/// Set the O_NONBLOCK flag on the open file description.
		NONBLOCK = IN_NONBLOCK,
		/// Set the O_CLOEXEC flag on the open file description.
		CLOEXEC  = IN_CLOEXEC,
	};

	using InitFlags = BitMask<InitFlag>;

	/// Unique identifier for a registered watch.
	/**
	 * `addWatch()` returns a WatchID which is used to match `Event`s
	 * returned from `readEvent()` to registered watches.
	 *
	 * Not every event contains a valid WatchID e.g. if
	 * EventFlag::OVERFLOW occurs then it is set to WatchID::INVALID.
	 **/
	enum class WatchID : int {
		INVALID = -1
	};

	/// A cookie value used in inotify events.
	/**
	 * A cookie is used to connect related inotify events with each other.
	 * Currently this only happens for related EventType::MOVED_TO and
	 * EventType::MOVED_FROM events. Otherwise Cookie::NONE is supplied.
	 *
	 * While MOVED_TO and MOVED_FROM typically appear directly after each
	 * other there are no hard guarantees by the kernel that this will
	 * always be the case. The application should be prepared for a delay
	 * in the generation of the corresponding event with a matching
	 * cookie.
	 **/
	enum class Cookie : uint32_t {
		NONE = 0
	};

	/// Description of a single inotify event.
	/**
	 * Instances of this type can only be obtained via
	 * INotify::readEvent() and INotify::tryReadEvent(). The objects are
	 * backed by internal INotify memory and are only valid until the next
	 * call to one of the readEvent() functions at the INotify instance it
	 * was obtained from, or until the INotify instance it was obtained
	 * from is destroyed.
	 **/
	struct Event {

		/// The ID which was returned from INotify::addWatch().
		/**
		 * Some synthetic events like EventFlag::OVERFLOW set
		 * WatchID::INVALID here.
		 **/
		WatchID id() const {
			return WatchID{m_ev->wd};
		}

		/// \see Cookie
		Cookie cookie() const {
			return Cookie{m_ev->cookie};
		}

		/// The events which occurred, usually only a single entry.
		/**
		 * Only a single event type is expected to be set here, but
		 * the inotify API does not guarantee this, thus a mask of
		 * EventTypes is used in the API to cover possible future
		 * changes in inotify.
		 *
		 * In the case of synthetic events it can happen that no event
		 * at all is set in this mask e.g. when EventFlag::OVERFLOW
		 * or EventFlag::IGNORED occur.
		 **/
		EventTypes event() const {
			return EventTypes{m_ev->mask & IN_ALL_EVENTS};
		}

		/// Additional flags describing the event.
		EventFlags flags() const {
			return EventFlags{m_ev->mask & (~IN_ALL_EVENTS)};
		}

		/// The name of the file the event is about.
		/**
		 * The name is only provided In case the event is a child of a
		 * watched directory, otherwise this will be an empty string.
		 **/
		std::string_view name() const {
			if (m_ev->len == 0)
				return {};

			std::string_view ret{m_ev->name, m_ev->len};

			/* len contains zero padding bytes, so look for the
			 * first non-zero bytes from the end of the string to
			 * correct the string_view's size. */
			return ret.substr(0, ret.find_last_not_of(char{0}) + 1);
		}

	protected:

		friend class INotify;

		explicit Event(const struct inotify_event *ev) :
			m_ev{ev} {
		}

		const struct inotify_event *m_ev = nullptr;
	};

public: // functions

	/// Create a new INotify instance
	/**
	 * This creates a new inotify file descriptor and stores it in the
	 * object. By default the file descriptor will have the O_CLOEXEC flag
	 * set, unless different `flags` are provided.
	 *
	 * The `io_buffer_size` determines the buffer size used during event
	 * read operations and thus influences memory usage and the maximum
	 * number of events that can be retrieved in a single readEvent()
	 * operation. The size should be at least `sizeof(struct
	 * inotify_event) + NAME_MAX + 1` to guarantee that a single event can
	 * be stored in the buffer under all circumstances.
	 *
	 * On error an ApiError containing one of the following Errno values
	 * is thrown:
	 *
	 * - Errno::INVALID: bad `flags` specified.
	 * - Errno::NO_MEMORY: out of kernel memory.
	 * - Errno::TOO_MANY_FILES: the user limit of maximum inotify
	 *   instances has been reached or the per-process limit of maximum
	 *   file descriptors has been reached.
	 * - Errno::TOO_MANY_FILES_IN_SYS: the system-wide limit of maximum
	 *   number of open files has been reached.
	 **/
	explicit INotify(
			const size_t io_buffer_size = 8192,
			const InitFlags flags = InitFlag::CLOEXEC);

	/// Add a path to be watched to the current INotify instance.
	/**
	 * The given `path` will be watched for all the events set in `mask`.
	 * The given `flags` additionally control the behaviour of the watch
	 * and the events it reports.
	 *
	 * On success a new WatchID is returned. This ID will be set in any
	 * Event structures returned from readEvent() for being able to
	 * connect events to watches. It can also be used to remove the watch
	 * at a later time again via `removeWatch()`.
	 *
	 * On error an ApiError is thrown containing one of the following
	 * Errnos:
	 *
	 * - Errno::ACCESS: read permission is denied for `path`.
	 * - Errno::BAD_FD: invalid inotify file descriptor.
	 * - Errno::EXISTS: WatchFlag::MASK_CREATE was given and a watch for
	 *   same path (inode) already exists.
	 * - Errno::FAULT: `path` points outside the addressable address
	 *   space of the process.
	 * - Errno::INVALID_ARG: `mask` contains no valid events, or
	 *   WatchFlag::MASK_CREATE and WatchFlag::MASK_ADD have both been
	 *   set, or the (inotify) file descriptor has the wrong type.
	 * - Errno::NAME_TOO_LONG: `path` is too long.
	 * - Errno::NO_ENTRY: a directory component in `path` does not exist
	 *   or is a dangling symbolic link.
	 * - Errno::NO_MEMORY: insufficient kernel memory.
	 * - Errno::NO_SPACE: the user limit on the total number of inotify
	 *   watches was reached or the kernel failed to allocate a needed
	 *   resource.
	 * - Errno::NOT_A_DIR: WatchFlag::ONLYDIR was set and `path` is not a
	 *   directory.
	 **/
	WatchID addWatch(const SysString path, const EventTypes mask, const WatchFlags flags = {});

	/// Remove a previously established WatchID.
	/**
	 * The watch will be removed from the inotify instance. An event with
	 * EventFlag::IGNORED will be generated for this watch.
	 *
	 * On error an ApiError is thrown containing one of the following
	 * Errnos:
	 *
	 * - Errno::BAD_FD: bad inotify file descriptor.
	 * - Errno::INVALID_ARG: `id` is not valid or the (inotify) file
	 *   descriptor is of the wrong type.
	 **/
	void removeWatch(const WatchID id);

	/// Read the next event from the event queue.
	/**
	 * The returned object is operating directly on internal data of the
	 * INotify instance. It is only valid until the next call to
	 * readEvent() or tryReadEvent() or until the INotify instance it was
	 * retrieved from is destroyed.
	 *
	 * This call will block when there are no events available unless
	 * InitFlag::NONBLOCK was set during construction of the INotify
	 * object. If the latter is the case and no event is available then an
	 * ApiError is thrown. Use tryReadEvent() if you want to avoid that.
	 *
	 * On error an ApiError containing one of the following Errnos is
	 * thrown:
	 *
	 * - Errno:INVALID_ARG: the buffer size is too small to read the next
	 *   event (see constructor `io_buffer_size`).
	 * - Errno::AGAIN: the inotify descriptor is set to non-blocking mode
	 *   and no event is currently available for reading.
	 *
	 * Additionally generic I/O errors can occur as for any other `read()`
	 * operation.
	 **/
	Event readEvent();

	/// Try to read an event from the event queue.
	/**
	 * This is a variant of readEvent() for use with a non-blocking
	 * INotify instance. In case no event is currently available
	 * std::nullopt is returned instead of throwing an exception.
	 **/
	std::optional<Event> tryReadEvent();

	/// Returns the underlying inotify file descriptor.
	/**
	 * This file descriptor can be used with select/poll/epoll to
	 * monitor for new events in an event based fashion. Furthermore the
	 * non-blocking and close-on-exec behaviour can be control during the
	 * lifetime of the INotify instance. Take care not to close this
	 * file descriptor, lest the INotify object will become unusable.
	 **/
	FileDescriptor fd() const {
		return m_notify_file.fd();
	}

protected: // functions

	int rawFD() const;

protected: // data

	/// A file operating on the descriptor returned from inotify_init().
	cosmos::File m_notify_file;
	/// The I/O buffer size configured during construction of the object.
	size_t m_io_buffer_size;
	/// Active event data stored by `readEvent()`.
	std::vector<uint8_t> m_buffer;
	/// The current offset in `m_buffer` where possibly additional events are to be found.
	size_t m_offset = 0;
};

} // end ns
