var annotated_dup =
[
    [ "cosmos", null, [
      [ "proc", null, [
        [ "PidInfo", "structcosmos_1_1proc_1_1PidInfo.html", null ]
      ] ],
      [ "pthread", null, [
        [ "ID", "classcosmos_1_1pthread_1_1ID.html", "classcosmos_1_1pthread_1_1ID" ]
      ] ],
      [ "term", null, [
        [ "BackColor", "structcosmos_1_1term_1_1BackColor.html", null ],
        [ "ColoredText", "structcosmos_1_1term_1_1ColoredText.html", null ],
        [ "ColoredTextT", "structcosmos_1_1term_1_1ColoredTextT.html", null ],
        [ "ColorSpec", "classcosmos_1_1term_1_1ColorSpec.html", null ],
        [ "FeatureBase", "classcosmos_1_1term_1_1FeatureBase.html", "classcosmos_1_1term_1_1FeatureBase" ],
        [ "FrontColor", "structcosmos_1_1term_1_1FrontColor.html", null ],
        [ "TextEffect", "classcosmos_1_1term_1_1TextEffect.html", null ],
        [ "TextEffectT", "structcosmos_1_1term_1_1TextEffectT.html", null ],
        [ "TextOnColorT", "structcosmos_1_1term_1_1TextOnColorT.html", null ]
      ] ],
      [ "ApiError", "classcosmos_1_1ApiError.html", "classcosmos_1_1ApiError" ],
      [ "BitMask", "classcosmos_1_1BitMask.html", "classcosmos_1_1BitMask" ],
      [ "ChildCloner", "classcosmos_1_1ChildCloner.html", "classcosmos_1_1ChildCloner" ],
      [ "Clock", "classcosmos_1_1Clock.html", "classcosmos_1_1Clock" ],
      [ "CloneArgs", "structcosmos_1_1CloneArgs.html", "structcosmos_1_1CloneArgs" ],
      [ "CompareCString", "structcosmos_1_1CompareCString.html", null ],
      [ "Condition", "classcosmos_1_1Condition.html", "classcosmos_1_1Condition" ],
      [ "ConditionMutex", "classcosmos_1_1ConditionMutex.html", null ],
      [ "CosmosError", "classcosmos_1_1CosmosError.html", "classcosmos_1_1CosmosError" ],
      [ "Directory", "classcosmos_1_1Directory.html", "classcosmos_1_1Directory" ],
      [ "DirEntry", "classcosmos_1_1DirEntry.html", "classcosmos_1_1DirEntry" ],
      [ "DirFD", "classcosmos_1_1DirFD.html", null ],
      [ "DirIterator", "classcosmos_1_1DirIterator.html", null ],
      [ "DirStream", "classcosmos_1_1DirStream.html", "classcosmos_1_1DirStream" ],
      [ "EventFile", "classcosmos_1_1EventFile.html", "classcosmos_1_1EventFile" ],
      [ "FDFile", "classcosmos_1_1FDFile.html", "classcosmos_1_1FDFile" ],
      [ "FifoSchedulerSettings", "classcosmos_1_1FifoSchedulerSettings.html", null ],
      [ "File", "classcosmos_1_1File.html", "classcosmos_1_1File" ],
      [ "FileBase", "classcosmos_1_1FileBase.html", "classcosmos_1_1FileBase" ],
      [ "FileDescriptor", "classcosmos_1_1FileDescriptor.html", "classcosmos_1_1FileDescriptor" ],
      [ "FileError", "classcosmos_1_1FileError.html", "classcosmos_1_1FileError" ],
      [ "FileMode", "classcosmos_1_1FileMode.html", "classcosmos_1_1FileMode" ],
      [ "FileStatus", "classcosmos_1_1FileStatus.html", "classcosmos_1_1FileStatus" ],
      [ "FileType", "classcosmos_1_1FileType.html", "classcosmos_1_1FileType" ],
      [ "FormattedNumber", "structcosmos_1_1FormattedNumber.html", "structcosmos_1_1FormattedNumber" ],
      [ "GroupInfo", "classcosmos_1_1GroupInfo.html", "classcosmos_1_1GroupInfo" ],
      [ "HexNum", "structcosmos_1_1HexNum.html", null ],
      [ "Identity", "structcosmos_1_1Identity.html", null ],
      [ "ILogger", "classcosmos_1_1ILogger.html", "classcosmos_1_1ILogger" ],
      [ "InfoBase", "classcosmos_1_1InfoBase.html", "classcosmos_1_1InfoBase" ],
      [ "Init", "structcosmos_1_1Init.html", null ],
      [ "Initable", "classcosmos_1_1Initable.html", null ],
      [ "InitData", "structcosmos_1_1InitData.html", null ],
      [ "InputOutputStreamAdaptor", "classcosmos_1_1InputOutputStreamAdaptor.html", "classcosmos_1_1InputOutputStreamAdaptor" ],
      [ "InputStreamAdaptor", "classcosmos_1_1InputStreamAdaptor.html", "classcosmos_1_1InputStreamAdaptor" ],
      [ "InternalError", "classcosmos_1_1InternalError.html", null ],
      [ "MemFile", "classcosmos_1_1MemFile.html", "classcosmos_1_1MemFile" ],
      [ "Mutex", "classcosmos_1_1Mutex.html", "classcosmos_1_1Mutex" ],
      [ "MutexGuard", "structcosmos_1_1MutexGuard.html", null ],
      [ "MutexReverseGuard", "structcosmos_1_1MutexReverseGuard.html", null ],
      [ "NamedBool", "classcosmos_1_1NamedBool.html", null ],
      [ "OctNum", "structcosmos_1_1OctNum.html", null ],
      [ "OtherSchedulerSettings", "classcosmos_1_1OtherSchedulerSettings.html", "classcosmos_1_1OtherSchedulerSettings" ],
      [ "OutputStreamAdaptor", "classcosmos_1_1OutputStreamAdaptor.html", "classcosmos_1_1OutputStreamAdaptor" ],
      [ "PasswdInfo", "classcosmos_1_1PasswdInfo.html", "classcosmos_1_1PasswdInfo" ],
      [ "PidFD", "classcosmos_1_1PidFD.html", null ],
      [ "Pipe", "classcosmos_1_1Pipe.html", "classcosmos_1_1Pipe" ],
      [ "Poller", "classcosmos_1_1Poller.html", "classcosmos_1_1Poller" ],
      [ "PosixThread", "classcosmos_1_1PosixThread.html", "classcosmos_1_1PosixThread" ],
      [ "ProcessFile", "classcosmos_1_1ProcessFile.html", "classcosmos_1_1ProcessFile" ],
      [ "ReadLockGuard", "structcosmos_1_1ReadLockGuard.html", null ],
      [ "RealTimeSchedulerSettings", "classcosmos_1_1RealTimeSchedulerSettings.html", "classcosmos_1_1RealTimeSchedulerSettings" ],
      [ "ResourceGuard", "classcosmos_1_1ResourceGuard.html", null ],
      [ "RoundRobinSchedulerSettings", "classcosmos_1_1RoundRobinSchedulerSettings.html", null ],
      [ "RuntimeError", "classcosmos_1_1RuntimeError.html", null ],
      [ "RWLock", "classcosmos_1_1RWLock.html", "classcosmos_1_1RWLock" ],
      [ "sched_attr", "structcosmos_1_1sched__attr.html", "structcosmos_1_1sched__attr" ],
      [ "SchedulerSettings", "classcosmos_1_1SchedulerSettings.html", "classcosmos_1_1SchedulerSettings" ],
      [ "SecretFile", "classcosmos_1_1SecretFile.html", "classcosmos_1_1SecretFile" ],
      [ "SecretMemFile", "classcosmos_1_1SecretMemFile.html", null ],
      [ "Signal", "classcosmos_1_1Signal.html", "classcosmos_1_1Signal" ],
      [ "SignalFD", "classcosmos_1_1SignalFD.html", "classcosmos_1_1SignalFD" ],
      [ "SigSet", "classcosmos_1_1SigSet.html", "classcosmos_1_1SigSet" ],
      [ "StdLogger", "classcosmos_1_1StdLogger.html", null ],
      [ "StopWatch", "classcosmos_1_1StopWatch.html", "classcosmos_1_1StopWatch" ],
      [ "StreamAdaptor", "classcosmos_1_1StreamAdaptor.html", "classcosmos_1_1StreamAdaptor" ],
      [ "StreamIO", "classcosmos_1_1StreamIO.html", "classcosmos_1_1StreamIO" ],
      [ "SubProc", "classcosmos_1_1SubProc.html", "classcosmos_1_1SubProc" ],
      [ "TempDir", "classcosmos_1_1TempDir.html", "classcosmos_1_1TempDir" ],
      [ "TempFile", "classcosmos_1_1TempFile.html", "classcosmos_1_1TempFile" ],
      [ "TermDimension", "structcosmos_1_1TermDimension.html", null ],
      [ "Terminal", "classcosmos_1_1Terminal.html", "classcosmos_1_1Terminal" ],
      [ "TimerFD", "classcosmos_1_1TimerFD.html", "classcosmos_1_1TimerFD" ],
      [ "TimeSpec", "classcosmos_1_1TimeSpec.html", "classcosmos_1_1TimeSpec" ],
      [ "UsageError", "classcosmos_1_1UsageError.html", null ],
      [ "WaitRes", "classcosmos_1_1WaitRes.html", "classcosmos_1_1WaitRes" ],
      [ "WouldBlock", "classcosmos_1_1WouldBlock.html", null ],
      [ "WriteLockGuard", "structcosmos_1_1WriteLockGuard.html", null ]
    ] ]
];