var annotated_dup =
[
    [ "cosmos", null, [
      [ "fs", null, [
        [ "CopyFileRangeParameters", "structcosmos_1_1fs_1_1CopyFileRangeParameters.html", null ]
      ] ],
      [ "mem", null, [
        [ "MapFlags", "classcosmos_1_1mem_1_1MapFlags.html", "classcosmos_1_1mem_1_1MapFlags" ],
        [ "MapSettings", "structcosmos_1_1mem_1_1MapSettings.html", "structcosmos_1_1mem_1_1MapSettings" ]
      ] ],
      [ "net", null, [
        [ "EndianNumber", "classcosmos_1_1net_1_1EndianNumber.html", "classcosmos_1_1net_1_1EndianNumber" ],
        [ "EndianTraits", "structcosmos_1_1net_1_1EndianTraits.html", null ],
        [ "EndianTraits< Endian::BIG >", "structcosmos_1_1net_1_1EndianTraits_3_01Endian_1_1BIG_01_4.html", null ],
        [ "EndianTraits< Endian::LITTLE >", "structcosmos_1_1net_1_1EndianTraits_3_01Endian_1_1LITTLE_01_4.html", null ],
        [ "RawIntTraits", "structcosmos_1_1net_1_1RawIntTraits.html", null ],
        [ "RawIntTraits< uint16_t, Endian::BIG >", "structcosmos_1_1net_1_1RawIntTraits_3_01uint16__t_00_01Endian_1_1BIG_01_4.html", null ],
        [ "RawIntTraits< uint16_t, Endian::LITTLE >", "structcosmos_1_1net_1_1RawIntTraits_3_01uint16__t_00_01Endian_1_1LITTLE_01_4.html", null ],
        [ "RawIntTraits< uint32_t, Endian::BIG >", "structcosmos_1_1net_1_1RawIntTraits_3_01uint32__t_00_01Endian_1_1BIG_01_4.html", null ],
        [ "RawIntTraits< uint32_t, Endian::LITTLE >", "structcosmos_1_1net_1_1RawIntTraits_3_01uint32__t_00_01Endian_1_1LITTLE_01_4.html", null ],
        [ "RawIntTraits< uint64_t, Endian::BIG >", "structcosmos_1_1net_1_1RawIntTraits_3_01uint64__t_00_01Endian_1_1BIG_01_4.html", null ],
        [ "RawIntTraits< uint64_t, Endian::LITTLE >", "structcosmos_1_1net_1_1RawIntTraits_3_01uint64__t_00_01Endian_1_1LITTLE_01_4.html", null ]
      ] ],
      [ "proc", null, [
        [ "PidInfo", "structcosmos_1_1proc_1_1PidInfo.html", null ]
      ] ],
      [ "pthread", null, [
        [ "ID", "classcosmos_1_1pthread_1_1ID.html", "classcosmos_1_1pthread_1_1ID" ]
      ] ],
      [ "ptrace", null, [
        [ "PeekSigInfo", "classcosmos_1_1ptrace_1_1PeekSigInfo.html", "classcosmos_1_1ptrace_1_1PeekSigInfo" ],
        [ "SyscallInfo", "structcosmos_1_1ptrace_1_1SyscallInfo.html", "structcosmos_1_1ptrace_1_1SyscallInfo" ]
      ] ],
      [ "signal", null, [
        [ "Stack", "classcosmos_1_1signal_1_1Stack.html", "classcosmos_1_1signal_1_1Stack" ]
      ] ],
      [ "term", null, [
        [ "BackColor", "structcosmos_1_1term_1_1BackColor.html", null ],
        [ "ColoredText", "structcosmos_1_1term_1_1ColoredText.html", null ],
        [ "ColoredTextT", "structcosmos_1_1term_1_1ColoredTextT.html", null ],
        [ "ColorSpec", "classcosmos_1_1term_1_1ColorSpec.html", null ],
        [ "FeatureBase", "classcosmos_1_1term_1_1FeatureBase.html", "classcosmos_1_1term_1_1FeatureBase" ],
        [ "FrontColor", "structcosmos_1_1term_1_1FrontColor.html", null ],
        [ "TextEffect", "classcosmos_1_1term_1_1TextEffect.html", null ],
        [ "TextEffectT", "structcosmos_1_1term_1_1TextEffectT.html", null ],
        [ "TextOnColorT", "structcosmos_1_1term_1_1TextOnColorT.html", null ]
      ] ],
      [ "AddressHints", "classcosmos_1_1AddressHints.html", "classcosmos_1_1AddressHints" ],
      [ "AddressInfo", "classcosmos_1_1AddressInfo.html", "classcosmos_1_1AddressInfo" ],
      [ "AddressInfoIterator", "structcosmos_1_1AddressInfoIterator.html", null ],
      [ "AddressInfoList", "classcosmos_1_1AddressInfoList.html", "classcosmos_1_1AddressInfoList" ],
      [ "AncillaryMessage", "classcosmos_1_1AncillaryMessage.html", null ],
      [ "ApiError", "classcosmos_1_1ApiError.html", "classcosmos_1_1ApiError" ],
      [ "BitMask", "classcosmos_1_1BitMask.html", "classcosmos_1_1BitMask" ],
      [ "ChildCloner", "classcosmos_1_1ChildCloner.html", "classcosmos_1_1ChildCloner" ],
      [ "Clock", "classcosmos_1_1Clock.html", "classcosmos_1_1Clock" ],
      [ "CloneArgs", "structcosmos_1_1CloneArgs.html", "structcosmos_1_1CloneArgs" ],
      [ "CompareCString", "structcosmos_1_1CompareCString.html", null ],
      [ "Condition", "classcosmos_1_1Condition.html", "classcosmos_1_1Condition" ],
      [ "ConditionMutex", "classcosmos_1_1ConditionMutex.html", null ],
      [ "CosmosError", "classcosmos_1_1CosmosError.html", "classcosmos_1_1CosmosError" ],
      [ "Directory", "classcosmos_1_1Directory.html", "classcosmos_1_1Directory" ],
      [ "DirEntry", "classcosmos_1_1DirEntry.html", "classcosmos_1_1DirEntry" ],
      [ "DirFD", "classcosmos_1_1DirFD.html", null ],
      [ "DirIterator", "classcosmos_1_1DirIterator.html", null ],
      [ "DirStream", "classcosmos_1_1DirStream.html", "classcosmos_1_1DirStream" ],
      [ "EventFile", "classcosmos_1_1EventFile.html", "classcosmos_1_1EventFile" ],
      [ "FamilyTraits", "structcosmos_1_1FamilyTraits.html", null ],
      [ "FamilyTraits< SocketFamily::INET >", "structcosmos_1_1FamilyTraits_3_01SocketFamily_1_1INET_01_4.html", null ],
      [ "FamilyTraits< SocketFamily::INET6 >", "structcosmos_1_1FamilyTraits_3_01SocketFamily_1_1INET6_01_4.html", null ],
      [ "FDFile", "classcosmos_1_1FDFile.html", "classcosmos_1_1FDFile" ],
      [ "FifoSchedulerSettings", "classcosmos_1_1FifoSchedulerSettings.html", null ],
      [ "File", "classcosmos_1_1File.html", "classcosmos_1_1File" ],
      [ "FileBase", "classcosmos_1_1FileBase.html", "classcosmos_1_1FileBase" ],
      [ "FileDescriptor", "classcosmos_1_1FileDescriptor.html", "classcosmos_1_1FileDescriptor" ],
      [ "FileError", "classcosmos_1_1FileError.html", "classcosmos_1_1FileError" ],
      [ "FileLock", "classcosmos_1_1FileLock.html", "classcosmos_1_1FileLock" ],
      [ "FileLockGuard", "structcosmos_1_1FileLockGuard.html", null ],
      [ "FileMode", "classcosmos_1_1FileMode.html", "classcosmos_1_1FileMode" ],
      [ "FileStatus", "classcosmos_1_1FileStatus.html", "classcosmos_1_1FileStatus" ],
      [ "FileType", "classcosmos_1_1FileType.html", "classcosmos_1_1FileType" ],
      [ "FormattedNumber", "structcosmos_1_1FormattedNumber.html", "structcosmos_1_1FormattedNumber" ],
      [ "GroupInfo", "classcosmos_1_1GroupInfo.html", "classcosmos_1_1GroupInfo" ],
      [ "HexNum", "structcosmos_1_1HexNum.html", null ],
      [ "Identity", "structcosmos_1_1Identity.html", null ],
      [ "ILogger", "classcosmos_1_1ILogger.html", "classcosmos_1_1ILogger" ],
      [ "InfoBase", "classcosmos_1_1InfoBase.html", "classcosmos_1_1InfoBase" ],
      [ "Init", "structcosmos_1_1Init.html", null ],
      [ "Initable", "classcosmos_1_1Initable.html", null ],
      [ "InitData", "structcosmos_1_1InitData.html", null ],
      [ "InputMemoryRegion", "structcosmos_1_1InputMemoryRegion.html", null ],
      [ "InputOutputStreamAdaptor", "classcosmos_1_1InputOutputStreamAdaptor.html", "classcosmos_1_1InputOutputStreamAdaptor" ],
      [ "InputStreamAdaptor", "classcosmos_1_1InputStreamAdaptor.html", "classcosmos_1_1InputStreamAdaptor" ],
      [ "InterfaceAddress", "classcosmos_1_1InterfaceAddress.html", "classcosmos_1_1InterfaceAddress" ],
      [ "InterfaceAddressIterator", "classcosmos_1_1InterfaceAddressIterator.html", null ],
      [ "InterfaceAddressList", "classcosmos_1_1InterfaceAddressList.html", "classcosmos_1_1InterfaceAddressList" ],
      [ "InterfaceEnumerator", "classcosmos_1_1InterfaceEnumerator.html", "classcosmos_1_1InterfaceEnumerator" ],
      [ "InterfaceInfo", "structcosmos_1_1InterfaceInfo.html", "structcosmos_1_1InterfaceInfo" ],
      [ "InterfaceIterator", "classcosmos_1_1InterfaceIterator.html", null ],
      [ "InternalError", "classcosmos_1_1InternalError.html", null ],
      [ "IOMemoryRegion", "structcosmos_1_1IOMemoryRegion.html", "structcosmos_1_1IOMemoryRegion" ],
      [ "iovec_const", "structcosmos_1_1iovec__const.html", null ],
      [ "IOVector", "classcosmos_1_1IOVector.html", "classcosmos_1_1IOVector" ],
      [ "IP4Address", "classcosmos_1_1IP4Address.html", "classcosmos_1_1IP4Address" ],
      [ "IP4Options", "classcosmos_1_1IP4Options.html", "classcosmos_1_1IP4Options" ],
      [ "IP4RawAddress", "classcosmos_1_1IP4RawAddress.html", null ],
      [ "IP6Address", "classcosmos_1_1IP6Address.html", "classcosmos_1_1IP6Address" ],
      [ "IP6Options", "classcosmos_1_1IP6Options.html", "classcosmos_1_1IP6Options" ],
      [ "IP6RawAddress", "structcosmos_1_1IP6RawAddress.html", null ],
      [ "IPAddressBase", "classcosmos_1_1IPAddressBase.html", "classcosmos_1_1IPAddressBase" ],
      [ "IPOptBase", "classcosmos_1_1IPOptBase.html", "classcosmos_1_1IPOptBase" ],
      [ "IPPort", "classcosmos_1_1IPPort.html", null ],
      [ "IPSocketT", "classcosmos_1_1IPSocketT.html", "classcosmos_1_1IPSocketT" ],
      [ "LinkLayerAddress", "classcosmos_1_1LinkLayerAddress.html", "classcosmos_1_1LinkLayerAddress" ],
      [ "ListenSocket", "classcosmos_1_1ListenSocket.html", "classcosmos_1_1ListenSocket" ],
      [ "MACAddress", "structcosmos_1_1MACAddress.html", null ],
      [ "MainContainerArgs", "classcosmos_1_1MainContainerArgs.html", "classcosmos_1_1MainContainerArgs" ],
      [ "MainNoArgs", "classcosmos_1_1MainNoArgs.html", "classcosmos_1_1MainNoArgs" ],
      [ "MainPlainArgs", "classcosmos_1_1MainPlainArgs.html", "classcosmos_1_1MainPlainArgs" ],
      [ "Mapping", "classcosmos_1_1Mapping.html", "classcosmos_1_1Mapping" ],
      [ "MemFile", "classcosmos_1_1MemFile.html", "classcosmos_1_1MemFile" ],
      [ "MessageHeaderBase", "classcosmos_1_1MessageHeaderBase.html", "classcosmos_1_1MessageHeaderBase" ],
      [ "msghdr_const", "structcosmos_1_1msghdr__const.html", null ],
      [ "Mutex", "classcosmos_1_1Mutex.html", "classcosmos_1_1Mutex" ],
      [ "MutexGuard", "structcosmos_1_1MutexGuard.html", null ],
      [ "MutexReverseGuard", "structcosmos_1_1MutexReverseGuard.html", null ],
      [ "NamedBool", "classcosmos_1_1NamedBool.html", null ],
      [ "no_init_t", "structcosmos_1_1no__init__t.html", null ],
      [ "OctNum", "structcosmos_1_1OctNum.html", null ],
      [ "OtherSchedulerSettings", "classcosmos_1_1OtherSchedulerSettings.html", "classcosmos_1_1OtherSchedulerSettings" ],
      [ "OutputMemoryRegion", "structcosmos_1_1OutputMemoryRegion.html", null ],
      [ "OutputStreamAdaptor", "classcosmos_1_1OutputStreamAdaptor.html", "classcosmos_1_1OutputStreamAdaptor" ],
      [ "PasswdInfo", "classcosmos_1_1PasswdInfo.html", "classcosmos_1_1PasswdInfo" ],
      [ "PidFD", "classcosmos_1_1PidFD.html", null ],
      [ "Pipe", "classcosmos_1_1Pipe.html", "classcosmos_1_1Pipe" ],
      [ "Poller", "classcosmos_1_1Poller.html", "classcosmos_1_1Poller" ],
      [ "PosixThread", "classcosmos_1_1PosixThread.html", "classcosmos_1_1PosixThread" ],
      [ "ProcessFile", "classcosmos_1_1ProcessFile.html", "classcosmos_1_1ProcessFile" ],
      [ "RangeError", "classcosmos_1_1RangeError.html", null ],
      [ "ReadLockGuard", "structcosmos_1_1ReadLockGuard.html", null ],
      [ "RealTimeSchedulerSettings", "classcosmos_1_1RealTimeSchedulerSettings.html", "classcosmos_1_1RealTimeSchedulerSettings" ],
      [ "ReceiveMessageHeader", "classcosmos_1_1ReceiveMessageHeader.html", "classcosmos_1_1ReceiveMessageHeader" ],
      [ "ResolveError", "classcosmos_1_1ResolveError.html", "classcosmos_1_1ResolveError" ],
      [ "ResourceGuard", "classcosmos_1_1ResourceGuard.html", null ],
      [ "RoundRobinSchedulerSettings", "classcosmos_1_1RoundRobinSchedulerSettings.html", null ],
      [ "RuntimeError", "classcosmos_1_1RuntimeError.html", null ],
      [ "RWLock", "classcosmos_1_1RWLock.html", "classcosmos_1_1RWLock" ],
      [ "sched_attr", "structcosmos_1_1sched__attr.html", "structcosmos_1_1sched__attr" ],
      [ "SchedulerSettings", "classcosmos_1_1SchedulerSettings.html", "classcosmos_1_1SchedulerSettings" ],
      [ "SecretFile", "classcosmos_1_1SecretFile.html", "classcosmos_1_1SecretFile" ],
      [ "SecretMemFile", "classcosmos_1_1SecretMemFile.html", null ],
      [ "SendMessageHeader", "classcosmos_1_1SendMessageHeader.html", "classcosmos_1_1SendMessageHeader" ],
      [ "SigAction", "classcosmos_1_1SigAction.html", "classcosmos_1_1SigAction" ],
      [ "SigInfo", "classcosmos_1_1SigInfo.html", "classcosmos_1_1SigInfo" ],
      [ "Signal", "classcosmos_1_1Signal.html", "classcosmos_1_1Signal" ],
      [ "SignalFD", "classcosmos_1_1SignalFD.html", "classcosmos_1_1SignalFD" ],
      [ "SigSet", "classcosmos_1_1SigSet.html", "classcosmos_1_1SigSet" ],
      [ "Socket", "classcosmos_1_1Socket.html", "classcosmos_1_1Socket" ],
      [ "SocketAddress", "classcosmos_1_1SocketAddress.html", "classcosmos_1_1SocketAddress" ],
      [ "SocketErrorMessage", "classcosmos_1_1SocketErrorMessage.html", "classcosmos_1_1SocketErrorMessage" ],
      [ "SocketErrorT", "classcosmos_1_1SocketErrorT.html", "classcosmos_1_1SocketErrorT" ],
      [ "SocketOptions", "classcosmos_1_1SocketOptions.html", "classcosmos_1_1SocketOptions" ],
      [ "SockOptBase", "classcosmos_1_1SockOptBase.html", "classcosmos_1_1SockOptBase" ],
      [ "StdLogger", "classcosmos_1_1StdLogger.html", null ],
      [ "StopWatch", "classcosmos_1_1StopWatch.html", "classcosmos_1_1StopWatch" ],
      [ "StreamAdaptor", "classcosmos_1_1StreamAdaptor.html", "classcosmos_1_1StreamAdaptor" ],
      [ "StreamIO", "classcosmos_1_1StreamIO.html", "classcosmos_1_1StreamIO" ],
      [ "SubProc", "classcosmos_1_1SubProc.html", "classcosmos_1_1SubProc" ],
      [ "SysString", "structcosmos_1_1SysString.html", null ],
      [ "TCPClientSocketT", "classcosmos_1_1TCPClientSocketT.html", "classcosmos_1_1TCPClientSocketT" ],
      [ "TCPConnectionT", "classcosmos_1_1TCPConnectionT.html", "classcosmos_1_1TCPConnectionT" ],
      [ "TCPInfo", "structcosmos_1_1TCPInfo.html", null ],
      [ "TCPListenSocketT", "classcosmos_1_1TCPListenSocketT.html", "classcosmos_1_1TCPListenSocketT" ],
      [ "TCPOptions", "classcosmos_1_1TCPOptions.html", "classcosmos_1_1TCPOptions" ],
      [ "TempDir", "classcosmos_1_1TempDir.html", "classcosmos_1_1TempDir" ],
      [ "TempFile", "classcosmos_1_1TempFile.html", "classcosmos_1_1TempFile" ],
      [ "TermDimension", "structcosmos_1_1TermDimension.html", null ],
      [ "Terminal", "classcosmos_1_1Terminal.html", "classcosmos_1_1Terminal" ],
      [ "TimerFD", "classcosmos_1_1TimerFD.html", "classcosmos_1_1TimerFD" ],
      [ "TimeSpec", "classcosmos_1_1TimeSpec.html", "classcosmos_1_1TimeSpec" ],
      [ "Tracee", "classcosmos_1_1Tracee.html", "classcosmos_1_1Tracee" ],
      [ "Twice", "classcosmos_1_1Twice.html", null ],
      [ "TwiceIterator", "classcosmos_1_1TwiceIterator.html", null ],
      [ "UDPOptions", "classcosmos_1_1UDPOptions.html", "classcosmos_1_1UDPOptions" ],
      [ "UDPSocketT", "classcosmos_1_1UDPSocketT.html", "classcosmos_1_1UDPSocketT" ],
      [ "UnixAddress", "classcosmos_1_1UnixAddress.html", "classcosmos_1_1UnixAddress" ],
      [ "UnixClientSocket", "classcosmos_1_1UnixClientSocket.html", "classcosmos_1_1UnixClientSocket" ],
      [ "UnixConnection", "classcosmos_1_1UnixConnection.html", "classcosmos_1_1UnixConnection" ],
      [ "UnixCredentials", "structcosmos_1_1UnixCredentials.html", "structcosmos_1_1UnixCredentials" ],
      [ "UnixCredentialsMessage", "classcosmos_1_1UnixCredentialsMessage.html", null ],
      [ "UnixDatagramSocket", "classcosmos_1_1UnixDatagramSocket.html", "classcosmos_1_1UnixDatagramSocket" ],
      [ "UnixListenSocket", "classcosmos_1_1UnixListenSocket.html", "classcosmos_1_1UnixListenSocket" ],
      [ "UnixOptions", "classcosmos_1_1UnixOptions.html", "classcosmos_1_1UnixOptions" ],
      [ "UnixRightsMessage", "classcosmos_1_1UnixRightsMessage.html", "classcosmos_1_1UnixRightsMessage" ],
      [ "UnixSeqPacketClientSocket", "classcosmos_1_1UnixSeqPacketClientSocket.html", null ],
      [ "UnixSeqPacketListenSocket", "classcosmos_1_1UnixSeqPacketListenSocket.html", null ],
      [ "UnixStreamClientSocket", "classcosmos_1_1UnixStreamClientSocket.html", null ],
      [ "UnixStreamListenSocket", "classcosmos_1_1UnixStreamListenSocket.html", null ],
      [ "UsageError", "classcosmos_1_1UsageError.html", null ],
      [ "WouldBlock", "classcosmos_1_1WouldBlock.html", null ],
      [ "WriteLockGuard", "structcosmos_1_1WriteLockGuard.html", null ]
    ] ]
];