Import('env')

libenv = env.Clone()
public_includes = Dir(".").srcnode().abspath + "/../include"
# automatically include the export header to reduce noise in headers
libenv.Append(CCFLAGS = ["-include",  "cosmos/dso_export.h"])
libenv.Append(CCFLAGS="-fvisibility=hidden")
libenv.Append(CCFLAGS="-DCOSMOS_EXPORT")
libenv.Append(LINKFLAGS="-pthread")
libenv.Append(CPPPATH=["."])
libenv.Append(CPPPATH=public_includes)

libcosmos_srcs = env.GatherSources(suffixes=[".cxx"])

libcosmos = libenv.SharedLibrary(
    "cosmos",
    libcosmos_srcs
)

env.RegisterLibConfig('libcosmos', libcosmos, {
    "CCFLAGS": ["-DCOSMOS_API="],
    "CPPPATH": [public_includes],
    "LINKFLAGS": ["-pthread"]
})
